spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "payment"
      auto-offset-reset: earliest
    properties:
      request.timeout.ms: 300000
      heartbeat.interval.ms: 1000
      max.poll.interval.ms: 900000
      max.poll.records: 100
      session.timeout.ms: 600000

  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  hibernate:
    ddl-auto: "none"
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/payments"
    username: "tech"
    password: "test"
    initialization-mode: "always"
    initialize: true